[package]
name = "console-interactive"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2021"

[dependencies.nx]
workspace = true
features = ["input", "fs", "vty", "rand"]

[package.metadata.nx.nro]
nacp = { default_name = "console-interactive", default_author = "XorTroll", version = "Example" }

[dependencies]
embedded-term = { git = "https://github.com/rcore-os/embedded-term", rev = "ce0fc1b30a883dba95f7d6ef794699100f178bd6", default-features = false }
